name: list

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19.4'

      - run: go mod download

      - env:
          GOPROXY: "proxy.golang.org"
        run: go list -m github.com/cardinalby/gozig@${{ github.ref_name }}
